#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# TZ KREE driver makefile.

ccflags-y += -I$(srctree)/include -I$(srctree)/include/trustzone -I$(srctree)/drivers/misc/mediatek/trustzone -Werror

obj-y += mediatek-rng.o

