SRC_NAME = trojan
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/trojan /usr/bin/trojan
	$(ROMFSINST) -p +x $(THISDIR)/cacert.pem /usr/bin/cacert.pem
