
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_c/inc

obj-$(CONFIG_USB_C_SWITCH_FUSB302) += fusb302/
obj-$(CONFIG_USB_C_SWITCH_SII70XX) += sii7033/
obj-$(CONFIG_USB_C_SWITCH_ANX7418) += anx7418/
obj-$(CONFIG_TCPC_RT1711H) += rt1711h_pd/
obj-$(CONFIG_USB_C_SWITCH_MT6336) += mt6336/
obj-$(CONFIG_USB_C_SWITCH_MT6392) += mt6392/
