#
# Copyright (C) 2016 MediaTek Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8127/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat

obj-y += mt_spm_mtcmos.o
obj-y += mt-smp.o
obj-y += hotplug.o
obj-y += mt-headsmp.o
obj-y += mt_hotplug.o
obj-y += mt_spm.o
obj-y += mt_cpufreq.o
obj-y += mt_cpuidle.o
obj-y += cpu_dormant-v7.o
obj-y += mt_sleep.o
obj-y += mt_spm_sleep.o
